#!/bin/bash

setxkbmap be
xsetroot -cursor_name left_ptr

xwallpaper --zoom $HOME/pictures/kamp.png

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 4
bspc config focused_border_color "#ebdbb2"
bspc config normal_border_color "#3c3836"

bspc config window_gap 10
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
