#!/bin/sh

setxkbmap be
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &
picom -b
dunst &

xwallpaper --zoom $HOME/dotfiles/wallpapers/dark.png
eww open bar

bspc monitor -d one two three four five

bspc config border_width 4
bspc config focused_border_color "#ebdbb2"
bspc config normal_border_color "#3c3836"

bspc config window_gap 5
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
