github.com:
    users:
        niceduckdev:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: niceduckdev
