#!/bin/sh

logfile="$HOME/.dkrc.log"
[ -d "$HOME/.local/share/xorg" ] && logfile="$HOME/.local/share/xorg/dkrc.log"
: > "$logfile"

setxkbmap be
pgrep sxhkd || sxhkd -c "$HOME/.config/dk/sxhkdrc" &
picom -b

{
	dkcmd set numws=10

	dkcmd set ws=_ apply layout=tile master=1 gap=10 msplit=0.5 ssplit=0.5

	dkcmd set focus_open=true focus_urgent=true focus_mouse=false

	dkcmd set tile_tohead=0 tile_hints=false

	dkcmd set win_minwh=50 win_minxy=10

	dkcmd set smart_gap=false smart_border=false

	dkcmd set obey_motif=true
	
	dkcmd set border width=3 outer_width=3 \
		colour \
		focus='#EBDBB2' \
		unfocus='#EBDBB2' \
		urgent='#EBDBB2' \
		outer_focus='#EBDBB2' \
		outer_unfocus='#EBDBB2' \
		outer_urgent='#EBDBB2'
} >> "$logfile" 2>&1

if grep -q 'error:' "$logfile"; then
	hash notify-send && notify-send -t 0 -u critical "dkrc has errors" \
		"$(awk '/error:/ {sub(/^error: /, ""); gsub(/</, "\<"); print}' "$logfile")"
	exit 1
fi

exit 0

