#!/usr/bin/sh

setxkbmap be
xsetroot -cursor_name left_ptr
pgrep sxhkd || sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

picom -b
eww open bar
feh --bg-scale $HOME/pictures/kamp-2024.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 3
bspc config focused_border_color "#ebdbb2"
bspc config normal_border_color "#282828"

bspc config window_gap 5
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
