#!/usr/bin/sh

setxkbmap be
xsetroot -cursor_name left_ptr

pgrep sxhkd || sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &
picom -b --config $HOME/.config/bspwm/picom.conf

xwallpaper --zoom $HOME/pictures/kamp-2024.png
eww open bar

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 4
bspc config focused_border_color "#ebdbb2"
bspc config normal_border_color "#3c3836"

bspc config window_gap 10
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
