#!/usr/bin/sh

xsetroot -cursor_name left_ptr &
feh --bg-scale $HOME/pictures/kamp-2024.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 3
bspc config normal_border_color "#3C3836"
bspc config focused_border_color "#EBDBB2"

bspc config window_gap 5

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
